# Engine configuration for message classification
# Controls which rule engines are enabled and their settings

engines:
  keyword_engine:
    enabled: true
    config_file: "config/classification/keywords.yaml"
    description: "Keyword-based classification using weighted terms"

  pattern_engine:
    enabled: true
    config_file: "config/classification/patterns.yaml"
    description: "Pattern-based classification using regex matching"

  service_category_engine:
    enabled: false
    config_file: "config/classification/service_categories.yaml"
    description: "Service category classification for specific trades"

  ai_engine:
    enabled: false
    model: "claude-3-sonnet"
    api_key_env: "ANTHROPIC_API_KEY"
    description: "AI-powered classification using Anthropic Claude"

# Global classification thresholds
thresholds:
  request_confidence: 0.6
  recommendation_confidence: 0.6
  unknown_fallback: 0.5