# Modern pre-commit configuration
# Using Ruff + MyPy only

default_language_version:
  python: python3.13

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the formatter first
      - id: ruff-format
        name: Ruff Formatter
        
      # Then run the linter with auto-fix
      - id: ruff
        name: Ruff Linter
        args: [--fix, --exit-non-zero-on-fix]

  # MyPy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: MyPy Type Checker
        additional_dependencies: 
          - pydantic>=2.0.0
          - pydantic-settings
          - types-python-dateutil
          - types-pyyaml
          - fastapi
          - structlog
        args: [--config-file=pyproject.toml]
        pass_filenames: false  # Run on all files
        language: system  # Use the project's virtual environment

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]