version: "0.2"
language: en-GB
ignorePaths:
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/.git/**"
  - "**/.pytest_cache/**"
  - "**/.ruff_cache/**"
  - "**/.mypy_cache/**"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/node_modules/**"
  - "**/.env*"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.egg-info/**"
  - "**/htmlcov/**"
  - "**/.coverage"
  - "**/poetry.lock"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/package-lock.json"
  - "**/yarn.lock"
dictionaries:
  - en-gb
  - python
  - python-common
  - typescript
  - node
  - html
  - css
  - bash
  - companies
  - softwareTerms
  - misc
  - project-words
dictionaryDefinitions:
  - name: project-words
    path: ./.cspell-project-words.txt
    addWords: true
words:
  - abac
  - abstractmethod
  - ack
  - addon
  - addons
  - adoc
  - aggregateroot
  - alembic
  - alloc
  - amqp
  - anaconda
  - analyse
  - analysed
  - analysing
  - ansible
  - anticorruption
  - anyio
  - anymore
  - api
  - apikey
  - apis
  - argocd
  - args
  - arp
  - asciidoc
  - asgi
  - async
  - asyncio
  - attr
  - attrs
  - auth
  - authn
  - authorisation
  - authorise
  - authorised
  - authorising
  - authz
  - autouse
  - autowired
  - avro
  - await
  - basemodel
  - bash
  - behaviour
  - behaviours
  - bgp
  - bib
  - bibtex
  - bigtable
  - bitbucket
  - boundedcontext
  - buildkite
  - callback
  - calloc
  - caplog
  - capsys
  - CASESENSITIVE
  - cassandra
  - categorisation
  - categorise
  - categorised
  - categorising
  - cb
  - cdn
  - celery
  - centre
  - centred
  - centres
  - chatterbridge
  - choreography
  - cicd
  - circleci
  - classmethod
  - cmake
  - cockroachdb
  - codeclimate
  - codecov
  - colour
  - colours
  - compose
  - conda
  - conda-forge
  - conf
  - config
  - configdict
  - confloat
  - conftest
  - conint
  - conlist
  - conset
  - consistency
  - const
  - constr
  - consts
  - consul
  - containerd
  - coro
  - coroutine
  - cors
  - couchdb
  - coverage
  - coveralls
  - cpy
  - cqrs
  - crio
  - crud
  - csrf
  - css
  - ctx
  - customisation
  - customise
  - customised
  - customising
  - cwr
  - datadog
  - datetime
  - datetimez
  - ddos
  - dealloc
  - decodable
  - decoupled
  - defence
  - defences
  - deinit
  - deleter
  - dependency
  - depends
  - Deployability
  - deprecated
  - deserialisable
  - deserialisation
  - deserialise
  - deserialised
  - deserialising
  - dhcp
  - distutils
  - dns
  - docker
  - dockerfile
  - dockerignore
  - docstrings
  - doi
  - domainmodel
  - dos
  - dto
  - dtos
  - dynamodb
  - ean
  - ece
  - editorconfig
  - eigrp
  - elasticsearch
  - elem
  - elems
  - elif
  - emailstr
  - encodable
  - endif
  - entityid
  - enum
  - enums
  - env
  - err
  - errmsg
  - errno
  - eslintrc
  - eventsourcing
  - eventual
  - exc
  - faker
  - fastapi
  - favour
  - favoured
  - favourite
  - favourites
  - favours
  - field
  - fin
  - finalisation
  - finalise
  - finalised
  - finalising
  - firestore
  - fish
  - fixme
  - fixture
  - fixtures
  - flake8
  - fluentbit
  - fluentd
  - fn
  - fqdn
  - ftp
  - func
  - FURB
  - getter
  - github
  - gitignore
  - gitlab
  - gitops
  - gradle
  - grafana
  - graphql
  - greenapi
  - greenlet
  - grpc
  - guid
  - gunicorn
  - gyp
  - gypi
  - hack
  - hatch
  - hazelcast
  - helper
  - helpers
  - hexagonal
  - hmac
  - honour
  - honoured
  - honours
  - htm
  - html
  - htmlcov
  - http
  - https
  - httpurl
  - httpx
  - hypercorn
  - icmp
  - idempotency
  - idempotent
  - idor
  - idx
  - ifdef
  - ifndef
  - imap
  - impl
  - indices
  - init
  - initialisation
  - initialise
  - initialised
  - initialising
  - injectable
  - instanceof
  - ipvanyaddress
  - ipvanyinterface
  - ipvanynetwork
  - isbn
  - isort
  - istio
  - jaeger
  - jenkins
  - js
  - json
  - jsonable
  - jsonify
  - jsonl
  - jsonrpc
  - jsx
  - jwt
  - kafka
  - kibana
  - kubectl
  - kubernetes
  - kwargs
  - labour
  - laboured
  - labours
  - latex
  - layered
  - ldap
  - less
  - lfi
  - licence
  - licenced
  - licences
  - lifespan
  - linkerd
  - logstash
  - makefile
  - malloc
  - mamba
  - mambaforge
  - María
  - mariadb
  - maven
  - md
  - mdx
  - memcached
  - metaclass
  - microservice
  - microservices
  - middleware
  - middlewares
  - miniconda
  - miniforge
  - mitm
  - mixin
  - mixins
  - mock
  - mocked
  - mocker
  - mocking
  - mocks
  - modularised
  - mongodb
  - monkeypatch
  - monorepo
  - mqtt
  - msg
  - msgpack
  - msgs
  - mtls
  - mypy
  - mysql
  - nack
  - namespace
  - namespaces
  - nats
  - ndjson
  - neighbour
  - neighbourhood
  - neighbourhoods
  - neighbours
  - newrelic
  - nok
  - nomad
  - nonexistent
  - noop
  - normalisation
  - normalise
  - normalised
  - normalising
  - notanemail
  - nox
  - npm
  - nullopt
  - nullptr
  - oauth
  - offence
  - offences
  - oidc
  - ok
  - onion
  - opensearch
  - opentelemetry
  - optimisation
  - optimise
  - optimised
  - optimising
  - opts
  - orchestration
  - organisation
  - organisations
  - organise
  - organised
  - organiser
  - organisers
  - organising
  - ospf
  - otel
  - otlp
  - Overengineered
  - param
  - parametrize
  - parametrized
  - parametrizing
  - params
  - parquet
  - parsable
  - parseable
  - pbac
  - pdm
  - Perflint
  - pipenv
  - pipfile
  - plugin
  - plugins
  - pnpm
  - podman
  - poetry
  - pop
  - postgres
  - postgresql
  - pragma
  - prettierrc
  - prioritisation
  - prioritise
  - prioritised
  - prioritising
  - programme
  - programmed
  - programmes
  - prometheus
  - prop
  - property
  - props
  - protobuf
  - ps
  - ps1xml
  - psc
  - psd
  - psh
  - psm
  - psrc
  - pulsar
  - pulumi
  - py
  - pyc
  - pyd
  - pydantic
  - pyi
  - pylintrc
  - pyo
  - pypi
  - pytest
  - pytestmark
  - pyupgrade
  - pyw
  - pyx
  - pyz
  - pyzw
  - rabbitmq
  - rbac
  - rc
  - rce
  - realloc
  - redis
  - redoc
  - refactor
  - refurb
  - repr
  - req
  - reraises
  - res
  - resp
  - ret
  - returncode
  - retval
  - rfi
  - rip
  - rollbar
  - rpy
  - rst
  - rstp
  - ruff
  - saga
  - saml
  - sanitisation
  - sanitise
  - sanitised
  - sanitising
  - sass
  - scss
  - sëcrët
  - secretstr
  - semaphore
  - sentry
  - serialisable
  - serialisation
  - serialise
  - serialised
  - serialising
  - setter
  - setuptools
  - sftp
  - sh
  - singleton
  - sizeof
  - skipif
  - sku
  - smtp
  - sonarqube
  - spanner
  - sqlalchemy
  - sqli
  - ssh
  - sslv
  - ssrf
  - standardisation
  - standardise
  - standardised
  - standardising
  - starlette
  - staticmethod
  - stomp
  - stp
  - struct
  - structlog
  - structs
  - stub
  - stubbed
  - stubbing
  - stubs
  - stylus
  - svelte
  - swarm
  - syn
  - synchronisation
  - synchronise
  - synchronised
  - synchronising
  - tcp
  - teardown
  - terraform
  - tëst
  - tex
  - tidb
  - timedelta
  - timezone
  - tlsv
  - tmp
  - tmpdir
  - todo
  - tokenisation
  - tokenise
  - tokenised
  - tokenising
  - toml
  - tox
  - travisci
  - tryceratops
  - ts
  - tsx
  - twine
  - typedef
  - typedefs
  - typeof
  - typer
  - ubiquitouslanguage
  - udp
  - unauthorised
  - undef
  - unittest
  - urg
  - uri
  - url
  - urn
  - USDX
  - usecase
  - usefixtures
  - util
  - utils
  - uuid
  - uvicorn
  - validator
  - valueobject
  - valueobjects
  - venv
  - virtualenv
  - vlan
  - vpn
  - vue
  - websocket
  - websockets
  - wheel
  - wsgi
  - xfail
  - xhtml
  - xml
  - xmlrpc
  - xsrf
  - xss
  - xxe
  - yaml
  - yarn
  - yml
  - yugabyte
  - zipkin
  - zsh
ignoreRegExpList:
  - /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi
  - /[0-9a-f]{32}/gi
  - /[0-9a-f]{40}/gi
  - /[0-9a-f]{64}/gi
  - /\b[A-Z0-9]{20,}\b/g
  - /data:[^;]+;base64,[A-Za-z0-9+/]+=*/g
overrides:
  - filename: "**/*.py"
    language: python,en-gb
  - filename: "**/*.md"
    language: markdown,en-gb
  - filename: "**/*.yml"
    language: yaml,en-gb
  - filename: "**/*.yaml"
    language: yaml,en-gb
  - filename: "**/*.json"
    language: json,en-gb
  - filename: "**/Makefile"
    language: makefile,en-gb
  - filename: "**/*.sh"
    language: bash,en-gb
  - filename: "**/*.toml"
    language: toml,en-gb
