"""Shared utilities and exceptions for FastAPI template."""

from .exceptions import (
    ApplicationError,
    AuthenticationException,
    AuthorizationException,
    BusinessRuleViolationException,
    ConfigurationException,
    DatabaseException,
    EntityNotFoundException,
    ExternalAPIException,
    InvalidAPIKeyException,
    MessageDeliveryException,
    MissingEnvironmentVariableException,
    OrderNotFoundException,
    PersistenceException,
    ProductNotFoundException,
    RateLimitExceededException,
    RepositoryException,
    UserNotFoundException,
    ValidationException,
)

__all__ = [
    "ApplicationError",
    "AuthenticationException",
    "AuthorizationException",
    "BusinessRuleViolationException",
    "ConfigurationException",
    "DatabaseException",
    "EntityNotFoundException",
    "ExternalAPIException",
    "InvalidAPIKeyException",
    "MessageDeliveryException",
    "MissingEnvironmentVariableException",
    "OrderNotFoundException",
    "PersistenceException",
    "ProductNotFoundException",
    "RateLimitExceededException",
    "RepositoryException",
    "UserNotFoundException",
    "ValidationException",
]
