# Blacklisted terms for mention extraction
# These terms should be excluded from being considered as provider mentions

# Common pronouns and articles
pronouns_and_articles:
  - "I"
  - "you" 
  - "we"
  - "they"
  - "he"
  - "she"
  - "it"
  - "this"
  - "that"
  - "these"
  - "those"
  - "my"
  - "your"
  - "our"
  - "their"
  - "his"
  - "her"
  - "its"
  - "a"
  - "an"
  - "the"

# Common adjectives and adverbs (low-value terms)
descriptors:
  - "good"
  - "bad"
  - "better" 
  - "best"
  - "worse"
  - "worst"
  - "nice"
  - "great"
  - "excellent"
  - "poor"
  - "terrible"
  - "amazing"
  - "fantastic"
  - "awful"
  - "horrible"
  - "wonderful"
  - "perfect"
  - "okay"
  - "fine"

# Time-related terms
time_references:
  - "today"
  - "tomorrow"
  - "yesterday"
  - "now"
  - "later"
  - "soon"
  - "early"
  - "late"
  - "morning"
  - "afternoon"
  - "evening"
  - "night"
  - "day"
  - "week"
  - "month"
  - "year"
  - "time"
  - "hour"
  - "minute"
  - "second"
  - "monday"
  - "tuesday"
  - "wednesday"
  - "thursday" 
  - "friday"
  - "saturday"
  - "sunday"

# Generic action words
actions:
  - "do"
  - "does"
  - "did"
  - "doing"
  - "done"
  - "make"
  - "makes"
  - "made"
  - "making"
  - "get"
  - "gets"
  - "got"
  - "getting"
  - "go"
  - "goes"
  - "went"
  - "going"
  - "come"
  - "comes"
  - "came"
  - "coming"
  - "see"
  - "sees"
  - "saw"
  - "seeing"
  - "look"
  - "looks"
  - "looked"
  - "looking"

# Common filler words
filler_words:
  - "very"
  - "really"
  - "quite"
  - "rather"
  - "pretty"
  - "much"
  - "many"
  - "some"
  - "any"
  - "all"
  - "every"
  - "each"
  - "most"
  - "few"
  - "several"
  - "both"
  - "either"
  - "neither"

# Question words
question_words:
  - "who"
  - "what"
  - "when"
  - "where"
  - "why"
  - "how"
  - "which"
  - "whose"
  - "whom"

# Common business-sounding but non-specific terms
generic_business_terms:
  - "business"
  - "company" 
  - "service"
  - "services"
  - "work"
  - "working"
  - "job"
  - "jobs"
  - "task"
  - "tasks"
  - "project"
  - "projects"
  - "help"
  - "helping"
  - "support"
  - "customer"
  - "client"
  - "provider"
  - "contractor"

# Numbers and currency (too generic on their own)
generic_numbers:
  - "one"
  - "two"
  - "three"
  - "four"
  - "five"
  - "six"
  - "seven" 
  - "eight"
  - "nine"
  - "ten"
  - "hundred"
  - "thousand"
  - "million"
  - "rand"
  - "rands"
  - "cent"
  - "cents"
  - "price"
  - "cost"
  - "costs"
  - "expensive"
  - "cheap"
  - "affordable"

# Geographic terms that are too generic
generic_locations:
  - "here"
  - "there"
  - "somewhere"
  - "anywhere"
  - "everywhere" 
  - "nowhere"
  - "place"
  - "places"
  - "location"
  - "locations"
  - "area"
  - "areas"
  - "region"
  - "regions"
  - "local"
  - "nearby"
  - "close"
  - "far"

# Common WhatsApp message artifacts  
whatsapp_artifacts:
  - "message"
  - "messages"
  - "text"
  - "whatsapp"
  - "wa"
  - "group"
  - "groups"
  - "chat"
  - "chats"
  - "member"
  - "members"
  - "admin"
  - "admins"

# Common linking words and prepositions
connectors:
  - "and"
  - "or"
  - "but"
  - "so"
  - "yet"
  - "for"
  - "nor"
  - "at"
  - "in"
  - "on"
  - "by"
  - "to"
  - "of"
  - "as"
  - "is"
  - "are"
  - "was"
  - "were"
  - "be"
  - "been"
  - "being"
  - "have"
  - "has"
  - "had" 
  - "having"
  - "will"
  - "would"
  - "could"
  - "should"
  - "may"
  - "might"
  - "can"
  - "must"

# Greeting and politeness terms
social_terms:
  - "hi"
  - "hello"
  - "hey"
  - "thanks"
  - "thank"
  - "please"
  - "sorry"
  - "excuse"
  - "welcome"
  - "goodbye"
  - "bye"
  - "regards"
  - "cheers"
  - "kind"