# Location pattern extraction rules
# These patterns identify location references that may be associated with service providers

# South African cities and major areas
major_cities:
  cape_town_areas:
    - pattern: "Cape Town|CPT|CT"
      confidence_weight: 0.8
    - pattern: "Bellville|Parow|Goodwood|Brackenfell|Durbanville|Strand|Somerset West"
      confidence_weight: 0.85
    - pattern: "Sea Point|Green Point|Camps Bay|Clifton|Bantry Bay|Fresnaye"
      confidence_weight: 0.85
    - pattern: "Rondebosch|Claremont|Newlands|Wynberg|Constantia|Tokai"
      confidence_weight: 0.85
    - pattern: "Observatory|Salt River|Woodstock|District Six|Bo-Kaap"
      confidence_weight: 0.85
  
  johannesburg_areas:
    - pattern: "Johannesburg|JHB|Joburg|Jozi"
      confidence_weight: 0.8
    - pattern: "Sandton|Midrand|Randburg|Roodepoort|Soweto|Alexandra"
      confidence_weight: 0.85
    - pattern: "Rosebank|Melville|Parkhurst|Greenside|Parktown|Houghton"
      confidence_weight: 0.85

  durban_areas:
    - pattern: "Durban|DBN"
      confidence_weight: 0.8
    - pattern: "Umhlanga|Ballito|Pinetown|Westville|Chatsworth|Phoenix"
      confidence_weight: 0.85

  pretoria_areas:
    - pattern: "Pretoria|PTA|Tshwane"
      confidence_weight: 0.8
    - pattern: "Centurion|Hatfield|Menlyn|Brooklyn|Waterkloof|Arcadia"
      confidence_weight: 0.85

# Generic location indicators
location_indicators:
  directional:
    - pattern: "\\b(North|South|East|West|Northern|Southern|Eastern|Western)\\s+(Cape|Town|City|Area|Region|Suburb)\\b"
      confidence_weight: 0.75
    - pattern: "\\b(Upper|Lower|Central|Inner|Outer)\\s+([A-Z][a-z]+)\\b"
      confidence_weight: 0.70

  proximity:
    - pattern: "near\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)"
      confidence_weight: 0.75
    - pattern: "close to\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)"
      confidence_weight: 0.75
    - pattern: "around\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)"
      confidence_weight: 0.70

  coverage_areas:
    - pattern: "covers?\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*(?:,\\s*[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)*)"
      confidence_weight: 0.80
    - pattern: "services?\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*(?:(?:\\s+and|,)\\s+[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)*)"
      confidence_weight: 0.75
    - pattern: "areas?\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*(?:(?:\\s+and|,)\\s+[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)*)"
      confidence_weight: 0.75

# Property type references
property_types:
  residential:
    - pattern: "\\b(home|house|apartment|flat|townhouse|complex|estate)\\b"
      confidence_weight: 0.60
  
  commercial:
    - pattern: "\\b(office|shop|store|warehouse|factory|business|commercial|industrial)\\b"
      confidence_weight: 0.65

# Postal code patterns (South African format)
postal_codes:
  - pattern: "\\b[0-9]{4}\\b"
    confidence_weight: 0.70
    description: "4-digit postal codes"

# Address components
address_components:
  street_types:
    - pattern: "\\b([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)\\s+(Street|St|Road|Rd|Avenue|Ave|Drive|Dr|Lane|Ln|Close|Cl|Way|Crescent|Cres)\\b"
      confidence_weight: 0.80
  
  building_references:
    - pattern: "\\b([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)\\s+(Building|Tower|Centre|Center|Plaza|Park|Mall|Complex)\\b"
      confidence_weight: 0.75

# Geographic qualifiers that may indicate service coverage
coverage_qualifiers:
  - pattern: "\\b(local|area|regional|city-wide|province-wide|nationwide)\\b"
    confidence_weight: 0.65
  - pattern: "\\b(greater|metro|metropolitan)\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*)\\b"
    confidence_weight: 0.75

# Location-based service indicators
service_location_indicators:
  - pattern: "on-site|onsite|at your location|to your location|mobile service"
    confidence_weight: 0.80
  - pattern: "will travel|can travel|travel to"
    confidence_weight: 0.75

# Exclusion patterns (to avoid false positives)
exclusion_patterns:
  - "\\b(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\\b"
  - "\\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\\b"
  - "\\b(?:Location|Position|Place|Spot)\\s+(?:is|was|will be|has been)\\b"

# Validation constraints
validation:
  minimum_location_length: 2
  maximum_location_length: 50
  minimum_word_count: 1
  maximum_word_count: 4